CREATE OR REPLACE DYNAMIC TABLE COCO_WORKSHOP.PIPELINE_LAB.SILVER_AP_INVOICES
      TARGET_LAG = '1 hour'
      WAREHOUSE = COCO_WORKSHOP_WH
    AS
    SELECT
        'SAP'               AS SOURCE_SYSTEM,
        INVOICE_ID          AS SOURCE_INVOICE_ID,
        INVOICE_NUMBER,
        VENDOR_ID,
        VENDOR_NAME,
        INVOICE_DATE,
        DUE_DATE,
        INVOICE_AMOUNT,
        CURRENCY_CODE,
        PAYMENT_TERMS,
        PO_NUMBER,
        LINE_DESCRIPTION,
        GL_ACCOUNT,
        COST_CENTER,
        APPROVAL_STATUS     AS INVOICE_STATUS,
        CREATED_AT,
        SAP_COMPANY_CODE    AS SOURCE_ENTITY_CODE,
        SAP_DOCUMENT_TYPE   AS SOURCE_METADATA
    FROM COCO_WORKSHOP.SOURCE_DATA.BRONZE_SAP_AP_INVOICES

    UNION ALL

    SELECT
        'ORACLE'            AS SOURCE_SYSTEM,
        INV_ID              AS SOURCE_INVOICE_ID,
        INV_NUM             AS INVOICE_NUMBER,
        SUPPLIER_ID         AS VENDOR_ID,
        SUPPLIER_NAME       AS VENDOR_NAME,
        INV_DATE            AS INVOICE_DATE,
        PAYMENT_DUE_DATE    AS DUE_DATE,
        TOTAL_AMOUNT        AS INVOICE_AMOUNT,
        CURRENCY            AS CURRENCY_CODE,
        TERMS_CODE          AS PAYMENT_TERMS,
        PURCHASE_ORDER      AS PO_NUMBER,
        DESCRIPTION         AS LINE_DESCRIPTION,
        ACCOUNT_CODE        AS GL_ACCOUNT,
        DEPT_CODE           AS COST_CENTER,
        STATUS              AS INVOICE_STATUS,
        CREATION_DATE       AS CREATED_AT,
        ORACLE_ORG_ID       AS SOURCE_ENTITY_CODE,
        ORACLE_SOURCE       AS SOURCE_METADATA