SELECT SOURCE_SYSTEM,
           COUNT(*)           AS ROW_COUNT,
           MIN(INVOICE_DATE)  AS EARLIEST_INVOICE,
           MAX(INVOICE_DATE)  AS LATEST_INVOICE
    FROM   COCO_WORKSHOP.PIPELINE_LAB.SILVER_AP_INVOICES
    GROUP  BY SOURCE_SYSTEM
    ORDER  BY SOURCE_SYSTEM;